"""initial_schema

Revision ID: a4540615c800
Revises: 
Create Date: 2026-09-11 00:10:09.584873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4540615c800'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mittente', sa.String(length=255), nullable=False),
    sa.Column('destinatario', sa.String(length=255), nullable=False),
    sa.Column('oggetto', sa.String(length=300), nullable=False),
    sa.Column('corpo_html', sa.Text(), nullable=False),
    sa.Column('corpo_testo', sa.Text(), nullable=False),
    sa.Column('tipologia', sa.String(length=50), nullable=False),
    sa.Column('inviata', sa.Boolean(), nullable=False),
    sa.Column('errore', sa.Text(), nullable=True),
    sa.Column('link_azione', sa.String(length=500), nullable=True),
    sa.Column('data_invio', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_data_invio'), 'email_logs', ['data_invio'], unique=False)
    op.create_index(op.f('ix_email_logs_destinatario'), 'email_logs', ['destinatario'], unique=False)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_tipologia'), 'email_logs', ['tipologia'], unique=False)
    op.create_table('regioni',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codice_istat', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regioni_codice_istat'), 'regioni', ['codice_istat'], unique=True)
    op.create_index(op.f('ix_regioni_id'), 'regioni', ['id'], unique=False)
    op.create_index(op.f('ix_regioni_nome'), 'regioni', ['nome'], unique=True)
    op.create_table('ricerche_salvate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('criteri', sa.JSON(), nullable=False),
    sa.Column('descrizione_ricerca', sa.String(length=255), nullable=False),
    sa.Column('attiva', sa.Boolean(), nullable=False),
    sa.Column('data_creazione', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_invio', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ricerche_salvate_email'), 'ricerche_salvate', ['email'], unique=False)
    op.create_index(op.f('ix_ricerche_salvate_id'), 'ricerche_salvate', ['id'], unique=False)
    op.create_table('utenti',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=True),
    sa.Column('ragione_sociale', sa.String(length=200), nullable=True),
    sa.Column('partita_iva', sa.String(length=20), nullable=True),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=True),
    sa.Column('licenza_tulps', sa.String(length=100), nullable=True),
    sa.Column('ruolo', sa.Enum('PRIVATO', 'ARMERIA', 'MODERATORE', 'ADMIN', name='ruoloutente'), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('comune_id', sa.Integer(), nullable=True),
    sa.Column('indirizzo', sa.String(length=255), nullable=True),
    sa.Column('sito_web', sa.String(length=255), nullable=True),
    sa.Column('foto_profilo', sa.String(length=512), nullable=True),
    sa.Column('search_url_custom', sa.String(length=255), nullable=True),
    sa.Column('latitudine', sa.String(length=30), nullable=True),
    sa.Column('longitudine', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('data_registrazione', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utenti_comune_id'), 'utenti', ['comune_id'], unique=False)
    op.create_index(op.f('ix_utenti_email'), 'utenti', ['email'], unique=True)
    op.create_index(op.f('ix_utenti_id'), 'utenti', ['id'], unique=False)
    op.create_index(op.f('ix_utenti_nickname'), 'utenti', ['nickname'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('province',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sigla_automobilistica', sa.String(length=2), nullable=False),
    sa.Column('regione_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['regione_id'], ['regioni.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_province_id'), 'province', ['id'], unique=False)
    op.create_index(op.f('ix_province_nome'), 'province', ['nome'], unique=False)
    op.create_index(op.f('ix_province_sigla_automobilistica'), 'province', ['sigla_automobilistica'], unique=False)
    op.create_table('comuni',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('codice_istat', sa.String(length=6), nullable=True),
    sa.Column('cap', sa.String(length=5), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.Column('latitudine', sa.Float(), nullable=False),
    sa.Column('longitudine', sa.Float(), nullable=False),
    sa.Column('coordinate', app.models.geo.PostGISPoint(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['provincia_id'], ['province.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comuni_coordinate', 'comuni', ['coordinate'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_comuni_cap'), 'comuni', ['cap'], unique=False)
    op.create_index(op.f('ix_comuni_codice_istat'), 'comuni', ['codice_istat'], unique=False)
    op.create_index(op.f('ix_comuni_id'), 'comuni', ['id'], unique=False)
    op.create_index(op.f('ix_comuni_nome'), 'comuni', ['nome'], unique=False)
    op.create_table('annunci',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titolo', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('prezzo', sa.Float(), nullable=False),
    sa.Column('prezzo_originale', sa.Float(), nullable=True),
    sa.Column('stato', sa.Enum('BOZZA', 'IN_MODERAZIONE', 'PUBBLICATO', 'VENDUTO', 'ARCHIVIATO', 'RIFIUTATO', name='statoannuncio'), nullable=False),
    sa.Column('tipologia_inserzionista', sa.Enum('ARMERIA', 'PRIVATO', name='tipologiainserzionista'), nullable=False),
    sa.Column('tipologia_arma', sa.Enum('ARMA_CORTA', 'ARMA_LUNGA_RIGATA', 'CANNA_LISCIA', 'ARIA_COMPRESSA_LIBERA', 'ARIA_COMPRESSA_PIENA', 'ACCESSORIO_OTTICA', name='tipologiaarma'), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modello', sa.String(length=100), nullable=False),
    sa.Column('calibro', sa.String(length=50), nullable=False),
    sa.Column('classificazione', sa.Enum('COMUNE', 'SPORTIVA', 'CACCIA', 'NON_APPLICABILE', name='classificazionearma'), nullable=False),
    sa.Column('condizione', sa.Enum('NUOVO', 'USATO_OTTIMO', 'USATO_BUONO', 'DA_COLLEZIONE', name='condizionearma'), nullable=False),
    sa.Column('matricola_riservata', sa.String(length=100), nullable=True),
    sa.Column('comune_id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('galleria_immagini', sa.JSON(), nullable=False),
    sa.Column('link_esterno', sa.String(length=500), nullable=True),
    sa.Column('email_contatto', sa.String(length=255), nullable=False),
    sa.Column('telefono_contatto', sa.String(length=50), nullable=True),
    sa.Column('mostra_telefono_pubblico', sa.Boolean(), nullable=False),
    sa.Column('visualizzazioni', sa.Integer(), nullable=False),
    sa.Column('note_moderazione', sa.Text(), nullable=True),
    sa.Column('data_creazione', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comune_id'], ['comuni.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annunci_calibro'), 'annunci', ['calibro'], unique=False)
    op.create_index(op.f('ix_annunci_classificazione'), 'annunci', ['classificazione'], unique=False)
    op.create_index(op.f('ix_annunci_comune_id'), 'annunci', ['comune_id'], unique=False)
    op.create_index(op.f('ix_annunci_condizione'), 'annunci', ['condizione'], unique=False)
    op.create_index(op.f('ix_annunci_data_creazione'), 'annunci', ['data_creazione'], unique=False)
    op.create_index(op.f('ix_annunci_id'), 'annunci', ['id'], unique=False)
    op.create_index(op.f('ix_annunci_link_esterno'), 'annunci', ['link_esterno'], unique=False)
    op.create_index(op.f('ix_annunci_marca'), 'annunci', ['marca'], unique=False)
    op.create_index(op.f('ix_annunci_modello'), 'annunci', ['modello'], unique=False)
    op.create_index(op.f('ix_annunci_prezzo'), 'annunci', ['prezzo'], unique=False)
    op.create_index(op.f('ix_annunci_slug'), 'annunci', ['slug'], unique=True)
    op.create_index(op.f('ix_annunci_stato'), 'annunci', ['stato'], unique=False)
    op.create_index(op.f('ix_annunci_tipologia_arma'), 'annunci', ['tipologia_arma'], unique=False)
    op.create_index(op.f('ix_annunci_tipologia_inserzionista'), 'annunci', ['tipologia_inserzionista'], unique=False)
    op.create_index(op.f('ix_annunci_titolo'), 'annunci', ['titolo'], unique=False)
    op.create_index(op.f('ix_annunci_utente_id'), 'annunci', ['utente_id'], unique=False)
    op.create_table('poligoni_tiro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipologia', sa.String(length=50), nullable=False),
    sa.Column('comune_id', sa.Integer(), nullable=True),
    sa.Column('indirizzo', sa.String(length=255), nullable=True),
    sa.Column('latitudine', sa.Float(), nullable=False),
    sa.Column('longitudine', sa.Float(), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('sito_web', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('linee_tiro', sa.String(length=255), nullable=True),
    sa.Column('data_inserimento', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comune_id'], ['comuni.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poligoni_tiro_comune_id'), 'poligoni_tiro', ['comune_id'], unique=False)
    op.create_index(op.f('ix_poligoni_tiro_id'), 'poligoni_tiro', ['id'], unique=False)
    op.create_index(op.f('ix_poligoni_tiro_nome'), 'poligoni_tiro', ['nome'], unique=False)
    op.create_index(op.f('ix_poligoni_tiro_tipologia'), 'poligoni_tiro', ['tipologia'], unique=False)
    op.create_table('preferiti',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('annuncio_id', sa.Integer(), nullable=False),
    sa.Column('data_creazione', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annuncio_id'], ['annunci.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utente_id', 'annuncio_id', name='uq_utente_annuncio_preferito')
    )
    op.create_index(op.f('ix_preferiti_annuncio_id'), 'preferiti', ['annuncio_id'], unique=False)
    op.create_index(op.f('ix_preferiti_id'), 'preferiti', ['id'], unique=False)
    op.create_index(op.f('ix_preferiti_utente_id'), 'preferiti', ['utente_id'], unique=False)
    op.create_table('segnalazioni_annunci',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annuncio_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=100), nullable=False),
    sa.Column('dettagli', sa.Text(), nullable=False),
    sa.Column('email_segnalatore', sa.String(length=255), nullable=True),
    sa.Column('risolta', sa.Boolean(), nullable=False),
    sa.Column('azione_intrapresa', sa.String(length=100), nullable=True),
    sa.Column('data_creazione', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annuncio_id'], ['annunci.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segnalazioni_annunci_annuncio_id'), 'segnalazioni_annunci', ['annuncio_id'], unique=False)
    op.create_index(op.f('ix_segnalazioni_annunci_data_creazione'), 'segnalazioni_annunci', ['data_creazione'], unique=False)
    op.create_index(op.f('ix_segnalazioni_annunci_id'), 'segnalazioni_annunci', ['id'], unique=False)
    op.create_index(op.f('ix_segnalazioni_annunci_risolta'), 'segnalazioni_annunci', ['risolta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segnalazioni_annunci_risolta'), table_name='segnalazioni_annunci')
    op.drop_index(op.f('ix_segnalazioni_annunci_id'), table_name='segnalazioni_annunci')
    op.drop_index(op.f('ix_segnalazioni_annunci_data_creazione'), table_name='segnalazioni_annunci')
    op.drop_index(op.f('ix_segnalazioni_annunci_annuncio_id'), table_name='segnalazioni_annunci')
    op.drop_table('segnalazioni_annunci')
    op.drop_index(op.f('ix_preferiti_utente_id'), table_name='preferiti')
    op.drop_index(op.f('ix_preferiti_id'), table_name='preferiti')
    op.drop_index(op.f('ix_preferiti_annuncio_id'), table_name='preferiti')
    op.drop_table('preferiti')
    op.drop_index(op.f('ix_poligoni_tiro_tipologia'), table_name='poligoni_tiro')
    op.drop_index(op.f('ix_poligoni_tiro_nome'), table_name='poligoni_tiro')
    op.drop_index(op.f('ix_poligoni_tiro_id'), table_name='poligoni_tiro')
    op.drop_index(op.f('ix_poligoni_tiro_comune_id'), table_name='poligoni_tiro')
    op.drop_table('poligoni_tiro')
    op.drop_index(op.f('ix_annunci_utente_id'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_titolo'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_tipologia_inserzionista'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_tipologia_arma'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_stato'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_slug'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_prezzo'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_modello'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_marca'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_link_esterno'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_id'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_data_creazione'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_condizione'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_comune_id'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_classificazione'), table_name='annunci')
    op.drop_index(op.f('ix_annunci_calibro'), table_name='annunci')
    op.drop_table('annunci')
    op.drop_index(op.f('ix_comuni_nome'), table_name='comuni')
    op.drop_index(op.f('ix_comuni_id'), table_name='comuni')
    op.drop_index(op.f('ix_comuni_codice_istat'), table_name='comuni')
    op.drop_index(op.f('ix_comuni_cap'), table_name='comuni')
    op.drop_index('idx_comuni_coordinate', table_name='comuni', postgresql_using='gist')
    op.drop_table('comuni')
    op.drop_index(op.f('ix_province_sigla_automobilistica'), table_name='province')
    op.drop_index(op.f('ix_province_nome'), table_name='province')
    op.drop_index(op.f('ix_province_id'), table_name='province')
    op.drop_table('province')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_utenti_nickname'), table_name='utenti')
    op.drop_index(op.f('ix_utenti_id'), table_name='utenti')
    op.drop_index(op.f('ix_utenti_email'), table_name='utenti')
    op.drop_index(op.f('ix_utenti_comune_id'), table_name='utenti')
    op.drop_table('utenti')
    op.drop_index(op.f('ix_ricerche_salvate_id'), table_name='ricerche_salvate')
    op.drop_index(op.f('ix_ricerche_salvate_email'), table_name='ricerche_salvate')
    op.drop_table('ricerche_salvate')
    op.drop_index(op.f('ix_regioni_nome'), table_name='regioni')
    op.drop_index(op.f('ix_regioni_id'), table_name='regioni')
    op.drop_index(op.f('ix_regioni_codice_istat'), table_name='regioni')
    op.drop_table('regioni')
    op.drop_index(op.f('ix_email_logs_tipologia'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_destinatario'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_data_invio'), table_name='email_logs')
    op.drop_table('email_logs')
    # ### end Alembic commands ###
