"""
Directory di armerie online italiane attive con licenza di Pubblica Sicurezza (T.U.L.P.S.).
Ciascuna armeria è mappata con la propria geolocalizzazione (Città, Provincia, Regione, Coordinate)
e con il motore di ricerca interno del proprio e-commerce.
"""

from typing import Any, Dict, List
from urllib.parse import quote

ARMERIE_TARGETS: List[Dict[str, Any]] = [
    {
        "id_slug": "armeria-colosseo-milano",
        "nome": "Armeria Colosseo",
        "ragione_sociale": "Armeria Colosseo Milano Srl",
        "email": "info@armeriacolosseo.it",
        "telefono": "+39 02 72000000",
        "licenza_tulps": "MI-TULPS-00412",
        "citta": "Milano",
        "provincia_sigla": "MI",
        "regione": "Lombardia",
        "latitudine": 45.4642,
        "longitudine": 9.1900,
        "piattaforma": "woocommerce",
        "base_url": "https://www.armeriacolosseo.it",
        "search_url_template": "https://www.armeriacolosseo.it/?s={query}&post_type=product",
        "link_pattern": "/prodotto/",
        "catalogo_urls": [
            "https://www.armeriacolosseo.it/categoria-prodotto/armi/",
            "https://www.armeriacolosseo.it/categoria-prodotto/armi/page/2/",
        ],
    },
    {
        "id_slug": "armeria-regina-conegliano",
        "nome": "Armeria Regina",
        "ragione_sociale": "Armeria Regina Srl",
        "email": "info@armeriaregina.it",
        "telefono": "+39 0438 980182",
        "licenza_tulps": "TV-TULPS-00994",
        "citta": "Conegliano",
        "provincia_sigla": "TV",
        "regione": "Veneto",
        "latitudine": 45.8856,
        "longitudine": 12.2964,
        "piattaforma": "prestashop",
        "base_url": "https://armeriaregina.it",
        "search_url_template": "https://armeriaregina.it/it/ricerca?controller=search&s={query}",
        "link_pattern": ".html",
        "catalogo_urls": [
            "https://armeriaregina.it/it/247-armi-fine-serie",
        ],
    },
    {
        "id_slug": "armeria-dionisi-ascoli",
        "nome": "Armeria Dionisi",
        "ragione_sociale": "Armeria Dionisi Sport Srl",
        "email": "info@armeriadionisi.it",
        "telefono": "+39 0736 258000",
        "licenza_tulps": "AP-TULPS-00388",
        "citta": "Ascoli Piceno",
        "provincia_sigla": "AP",
        "regione": "Marche",
        "latitudine": 42.8546,
        "longitudine": 13.5756,
        "piattaforma": "shopify",
        "base_url": "https://armeriadionisi.it",
        "search_url_template": "https://armeriadionisi.it/search?q={query}&type=product",
        "link_pattern": "/products/",
        "catalogo_urls": [
            "https://armeriadionisi.it/collections/fucili-caccia",
            "https://armeriadionisi.it/collections/armi-usate",
            "https://armeriadionisi.it/collections/pistole",
        ],
    },
    {
        "id_slug": "armeria-innocenti-prato",
        "nome": "Armeria Innocenti",
        "ragione_sociale": "Armeria Innocenti di Prato",
        "email": "info@armeriainnocenti.it",
        "telefono": "+39 0574 692222",
        "licenza_tulps": "PO-TULPS-00122",
        "citta": "Montemurlo",
        "provincia_sigla": "PO",
        "regione": "Toscana",
        "latitudine": 43.9261,
        "longitudine": 11.0422,
        "piattaforma": "woocommerce",
        "base_url": "https://armeriainnocenti.it",
        "search_url_template": "https://armeriainnocenti.it/?s={query}&post_type=product",
        "link_pattern": "/prodotto/",
        "catalogo_urls": [
            "https://armeriainnocenti.it/armi/armi-usate/",
        ],
    },
    {
        "id_slug": "armeria-ceccoli-sanmarino",
        "nome": "Armeria Ceccoli",
        "ragione_sociale": "Armeria Ceccoli San Marino",
        "email": "info@armeriaceccoli.com",
        "telefono": "+378 0549 991234",
        "licenza_tulps": "RN-TULPS-00821",
        "citta": "Rimini",
        "provincia_sigla": "RN",
        "regione": "Emilia-Romagna",
        "latitudine": 44.0678,
        "longitudine": 12.5695,
        "piattaforma": "prestashop",
        "base_url": "https://armeriaceccoli.com",
        "search_url_template": "https://armeriaceccoli.com/?s={query}",
        "link_pattern": ".html",
        "catalogo_urls": [
            "https://armeriaceccoli.com/armi.html",
        ],
    },
    {
        "id_slug": "armeria-fracassi-pavia",
        "nome": "Armeria Fracassi",
        "ragione_sociale": "Armeria Fracassi Pavia Srl",
        "email": "info@armeriafracassi.com",
        "telefono": "+39 0382 526200",
        "licenza_tulps": "PV-TULPS-00455",
        "citta": "Pavia",
        "provincia_sigla": "PV",
        "regione": "Lombardia",
        "latitudine": 45.1847,
        "longitudine": 9.1582,
        "piattaforma": "woocommerce",
        "base_url": "https://www.armeriafracassi.com",
        "search_url_template": "https://www.armeriafracassi.com/?s={query}&post_type=product",
        "link_pattern": "/prodotto/",
        "catalogo_urls": [
            "https://www.armeriafracassi.com/categoria-prodotto/armi/",
        ],
    },
    {
        "id_slug": "armeria-bersaglio-mobile",
        "nome": "Armeria Bersaglio Mobile",
        "ragione_sociale": "Bersaglio Mobile Reggio Emilia Srl",
        "email": "info@bersagliomobile.com",
        "telefono": "+39 0522 518880",
        "licenza_tulps": "RE-TULPS-00210",
        "citta": "Reggio Emilia",
        "provincia_sigla": "RE",
        "regione": "Emilia-Romagna",
        "latitudine": 44.6983,
        "longitudine": 10.6312,
        "piattaforma": "woocommerce",
        "base_url": "https://www.bersagliomobile.com",
        "search_url_template": "https://www.bersagliomobile.com/?s={query}&post_type=product",
        "link_pattern": "/prodotto/",
        "catalogo_urls": [
            "https://www.bersagliomobile.com/categoria-prodotto/armi/",
        ],
    },
    {
        "id_slug": "armeria-barbuio-pordenone",
        "nome": "Armeria Barbuio",
        "ragione_sociale": "Armeria Barbuio Srl",
        "email": "info@armeriabarbuio.it",
        "telefono": "+39 0434 572200",
        "licenza_tulps": "PN-TULPS-00331",
        "citta": "Pordenone",
        "provincia_sigla": "PN",
        "regione": "Friuli-Venezia Giulia",
        "latitudine": 45.9566,
        "longitudine": 12.6606,
        "piattaforma": "woocommerce",
        "base_url": "https://www.armeriabarbuio.it",
        "search_url_template": "https://www.armeriabarbuio.it/?s={query}&post_type=product",
        "link_pattern": "/prodotto/",
        "catalogo_urls": [
            "https://www.armeriabarbuio.it/categoria-prodotto/armi/",
        ],
    },
    {
        "id_slug": "armeria-tomei-roma",
        "nome": "Armeria Tomei",
        "ragione_sociale": "Armeria Tomei Roma Srl",
        "email": "info@armeriatomei.it",
        "telefono": "+39 06 70476483",
        "licenza_tulps": "RM-TULPS-00519",
        "citta": "Roma",
        "provincia_sigla": "RM",
        "regione": "Lazio",
        "latitudine": 41.9028,
        "longitudine": 12.4964,
        "piattaforma": "woocommerce",
        "base_url": "https://www.armeriatomei.it",
        "search_url_template": "https://www.armeriatomei.it/?s={query}&post_type=product",
        "link_pattern": "/prodotto/",
        "catalogo_urls": [
            "https://www.armeriatomei.it/categoria-prodotto/armi/",
        ],
    },
    {
        "id_slug": "armeria-paoletti-arezzo",
        "nome": "Armeria Paoletti",
        "ragione_sociale": "Armeria Paoletti Srl",
        "email": "info@armeriapaoletti.it",
        "telefono": "+39 0575 355000",
        "licenza_tulps": "AR-TULPS-00188",
        "citta": "Arezzo",
        "provincia_sigla": "AR",
        "regione": "Toscana",
        "latitudine": 43.4632,
        "longitudine": 11.8796,
        "piattaforma": "woocommerce",
        "base_url": "https://armeriapaoletti.it",
        "search_url_template": "https://armeriapaoletti.it/?s={query}&post_type=product",
        "link_pattern": "/prodotto/",
        "catalogo_urls": [
            "https://armeriapaoletti.it/categoria-prodotto/armi-usate/",
        ],
    },
    {
        "id_slug": "armeria-jolly-cuneo",
        "nome": "Armeria Jolly",
        "ragione_sociale": "Armeria Jolly Snc",
        "email": "info@armeriajolly.it",
        "telefono": "+39 0171 692000",
        "licenza_tulps": "CN-TULPS-00277",
        "citta": "Cuneo",
        "provincia_sigla": "CN",
        "regione": "Piemonte",
        "latitudine": 44.3845,
        "longitudine": 7.5427,
        "piattaforma": "woocommerce",
        "base_url": "https://armeriajolly.it",
        "search_url_template": "https://armeriajolly.it/?s={query}&post_type=product",
        "link_pattern": "/prodotto/",
        "catalogo_urls": [
            "https://armeriajolly.it/categoria-prodotto/armi/",
        ],
    },
    {
        "id_slug": "armeria-casabella-genova",
        "nome": "Armeria Casabella",
        "ragione_sociale": "Armeria Casabella Srl",
        "email": "info@armeriacasabella.it",
        "telefono": "+39 010 595600",
        "licenza_tulps": "GE-TULPS-00344",
        "citta": "Genova",
        "provincia_sigla": "GE",
        "regione": "Liguria",
        "latitudine": 44.4056,
        "longitudine": 8.9463,
        "piattaforma": "woocommerce",
        "base_url": "https://www.armeriacasabella.it",
        "search_url_template": "https://www.armeriacasabella.it/?s={query}&post_type=product",
        "link_pattern": "/prodotto/",
        "catalogo_urls": [
            "https://www.armeriacasabella.it/categoria-prodotto/armi/",
        ],
    },
    {
        "id_slug": "armeria-lugli-modena",
        "nome": "Armeria Lugli",
        "ragione_sociale": "Armeria Lugli Srl",
        "email": "info@armerialugli.it",
        "telefono": "+39 059 217000",
        "licenza_tulps": "MO-TULPS-00192",
        "citta": "Modena",
        "provincia_sigla": "MO",
        "regione": "Emilia-Romagna",
        "latitudine": 44.6471,
        "longitudine": 10.9252,
        "piattaforma": "prestashop",
        "base_url": "https://www.armerialugli.it",
        "search_url_template": "https://www.armerialugli.it/it/module/iqitsearch/searchiqit?s={query}",
        "link_pattern": ".html",
        "catalogo_urls": [
            "https://www.armerialugli.it/it/12-armi-usate",
        ],
    },
]


def build_search_url(armeria: Dict[str, Any], query: str) -> str:
    """Formatta l'URL di ricerca dell'armeria specificata."""
    template = armeria.get("search_url_template", "")
    return template.format(query=quote(query))
